### ISSUE TITLE
[Feature]: 建议支持自己通过命令行或者配置文件来配置VERSION_TEMPLATE使bdsdown支持访问其他人配置的镜像

### ISSUE THREAD

**Issue by n15421** [LiteLDev/bdsdown#6]
### Is your feature request related to a problem? Please describe.

国内**大部分**网络下载bds很困难

### Describe the solution you'd like

可以选择加一个配置文件，以设定mirror，然后程序在下载bds时自动将https://minecraft.azureedge.net 替换成配置文件内mirror QwQ

### Describe alternatives you've considered

让用户在使用lip安装ll3前把预定配置文件放到根目录，然后等到bdsdown开始运行时读取配置文件来使用镜像加速

**Comment by futrime** [comment]
@KawaiiNahida

**Comment by n15421** [comment]
我们这头目前有一个做bds下载源站的镜像的意愿

**Comment by Jasonzyt** [comment]
![43845ef09470e83edebe0f882c91e05a](https://github.com/LiteLDev/bdsdown/assets/66063199/f729af25-2d6f-4d89-bd24-721523c2bf71)

**Comment by n15421** [comment]
那就建议支持读取系统http代理

**Comment by n15421** [comment]
如果不把国内用户当人可以当我没说

**Comment by ShrBox** [comment]
> 那就建议支持读取系统http代理

自行设置`HTTP_PROXY`和`HTTPS_PROXY`变量

**Comment by n15421** [comment]
我的问题，忘记提前测试了，确实通过set http_proxy进行指定代理
也希望ll工具链的优化越来越好
